### ISSUE TITLE
Add CocoaPods link support

### ISSUE THREAD

**Issue by hukid** [square/react-native-square-reader-sdk#21]
The plugin isn't configured to be able to be linked with cocoaPods, need up the podsepc to support that.

**Comment by kalaren** [comment]
Fairly new to react native, is this the issue I'm running into?
App builds fine locally. Trying to build on Microsoft App Center which needs cocoapods fails.

`ld: library not found for -lRNReaderSDK`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Removing libRNReaderSDK.a from Linked Frameworks and Libraries in Xcode and it builds fine in App Center, but obviously not a solution.

**Comment by StephenJosey** [comment]
Since the React Native plugin currently doesn't work with CocoaPods, it does sound like the same issue. We are still investigating on how to add CocoaPod support for linking this plugin. It's possible that this plugin could be configured to work with CocoaPods, but we don't currently have a solution for it. If you're able to resolve this issue, please let us know as we'd love to update this!

**Comment by geekruchika** [comment]
@kalaren 
Any solution you got to make it work?
Facing same problem.
